### ISSUE TITLE
Build a basic demo with Vue.js

### ISSUE THREAD

**Issue by gaurav** [phyloref/curation-tool#1]
The basic demo should be able to:

 - [x] List phylogenies
 - [x] List phyloreferences
 - [x] List internal and external specifiers for phyloreferences

**Comment by hlapp** [comment]
This sounds much more like a project than a task or issue? Have you considered creating a project “Demo with Electron” (or similar) for this repo?

**Comment by gaurav** [comment]
I have not -- but only because I've never used the Project features in Github yet! I'll check that out. This task is mainly for me to get a sense of how quickly we could build this in Electron, which I can show to everybody to make sure that we all agree on what this curation tool should look like and do. We can then design a full curation tool "correctly", i.e. by starting with a plan, list of required features, and so on, which I think will make more sense on a kanban board.

For this issue, I'd prefer to leave it here just to force myself to not overengineer this: I want a very simple demo that can read and write Phyloreferences from a paper.json file, and absolutely nothing more. As soon as I can check those three specific goals off, I'll make a pull request and call this task completed.

**Comment by gaurav** [comment]
After discussions in Durham, it looks more likely that this will be a web-based application than a locally installable application. I've accordingly modified this issue to "Build a basic demo with Vue.js", which is a technology Matt Yoder was talking about at the Phenoscape hackathon last month. If that doesn't work out, I'll look for another Javascript framework to use (starting with [this list](https://vuejs.org/v2/guide/comparison.html)).

As per Hilmar's comment above, I've also started a project for building a prototype: https://github.com/phyloref/curation-tool/projects/1
