### ISSUE TITLE
Provide the ability to validate PHYX files

### ISSUE THREAD

**Issue by gaurav** [phyloref/curation-tool#122]
We don't currently validate PHYX files -- unexpected content is simply ignored, and malformed expressions will result in a JavaScript error. Instead, we should look into validating PHYX files, either in the Curation Tool or on the command line. [JSON Schema](https://json-schema.org/) might be one way to do this. It would also be useful for the Clade Ontology if PHYX files could be distinguished from other JSON files, such as by including a particular `@context` or `@type` annotation.

**Comment by gaurav** [comment]
Moved to phyloref/phyx.js#16, closing it here.

**Comment by hlapp** [comment]
@gaurav did you notice that you can now _transfer_ issues? (It's on the right hand side, bottom, currently marked as in Beta.)

**Comment by gaurav** [comment]
Ooo, nice! I didn't notice that, thanks for letting me know!
