### ISSUE TITLE
Improve malformed Newick errors and detection

### ISSUE THREAD

**Issue by gaurav** [phyloref/curation-tool#41]
At the moment, malformed Newick strings are not displayed at all. This issue covers displaying an error message asking the user to fix the incorrect Newick string instead, as well as some quick methods for finding common sources of errors, such as by counting mismatched brackets. I have started work on this issue in [branch `newick_error_reporting`](https://github.com/phyloref/curation-tool/tree/newick_error_reporting).

**Comment by hlapp** [comment]
I agree it's worth trying to be specific about the causative error if the error is very easy to detect. However, I don't think we we should make going beyond that a priority right now. I.e., there are plenty of tree editors around that export Newick strings, and replicating their functionality even only partially shouldn't be a priority for us.
